"""
Seed management for Experimental Validity.

Per the frozen randomness rules for this project, five distinct sources
of randomness must never be collapsed into a single generic "seed":

    1. dataset randomness      (may be uncontrollable - see below)
    2. model initialization randomness
    3. minibatch / shuffle randomness
    4. evaluation randomness
    5. statistical resampling randomness (bootstrap, simulation)

This module defines the schema for tracking these separately. It does
NOT assume all five are controllable: Gohr's dataset generation uses
os.urandom() (see gohr.dataset), which is not seedable from Python's
random-number-generator layer at all. SeedSet.dataset_seed is therefore
Optional[int] and is None whenever the corresponding data was produced
by an unseedable generator - this module refuses to fabricate a value.
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from typing import Optional

import numpy as np


@dataclass(frozen=True)
class SeedSet:
    """
    Explicit, separated randomness sources for one replicate/condition.

    model_seed:
        Seed applied to Python's random, NumPy's global RNG, and (in the
        Gohr adapter) TensorFlow's global RNG immediately before model
        construction. Controls weight initialization and, because Keras
        shares the same global RNG state, also influences shuffle order
        when shuffle=True. See `same_training_shuffle_stream` guidance
        in framework.experiment - a shared model_seed does NOT by itself
        guarantee an identical shuffle stream if anything upstream
        consumes additional random draws first.

    dataset_seed:
        Seed used for dataset generation, if the generator is seedable.
        None means "this dataset was generated by an unseedable
        procedure" (e.g. os.urandom) - this is a valid, expected value
        for the Gohr case study, not a missing-data placeholder.

    shuffle_seed:
        Seed for minibatch/shuffle order, when the training framework
        exposes one independently of model_seed. None if the shuffle
        stream is not independently seedable (as with Gohr's Keras
        Model.fit(shuffle=...), where shuffling draws from the same
        global RNG state seeded via model_seed).

    evaluation_seed:
        Seed for any randomness in the evaluation procedure itself
        (e.g. if evaluation involved subsampling). None if evaluation
        is deterministic given a trained model and a fixed dataset.

    statistics_seed:
        Seed for statistical resampling (bootstrap, Monte Carlo power
        simulation). Always controllable and should always be recorded.
    """

    model_seed: Optional[int]
    dataset_seed: Optional[int]
    shuffle_seed: Optional[int]
    evaluation_seed: Optional[int]
    statistics_seed: Optional[int]

    def to_dict(self) -> dict:
        return {
            "model_seed": self.model_seed,
            "dataset_seed": self.dataset_seed,
            "shuffle_seed_if_available": self.shuffle_seed,
            "evaluation_seed_if_available": self.evaluation_seed,
            "statistics_seed": self.statistics_seed,
        }


def set_python_and_numpy_seed(seed: int) -> None:
    """
    Seed Python's `random` module and NumPy's global RNG.

    This is the generic, framework-level portion of seeding. Seeding
    any deep-learning framework's own RNG (e.g. tf.random.set_seed) is
    adapter-specific and lives in the Gohr adapter (gohr.train.set_seed),
    not here, to keep this module free of Gohr-specific or
    framework-specific assumptions.
    """
    random.seed(seed)
    np.random.seed(seed)


def statistics_rng(statistics_seed: int) -> np.random.Generator:
    """
    Construct an isolated NumPy Generator for statistical resampling
    (bootstrap / power simulation), independent of the global RNG state
    used for model seeding. Using a dedicated Generator instance (rather
    than the global np.random state) prevents statistical-analysis
    randomness from silently interacting with model/dataset randomness.
    """
    return np.random.default_rng(statistics_seed)
